version: '2'
services:
    amas2-app:
        image: amas2
        external_links:
            - amas2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/amas2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    amas2-mysql:
        extends:
            file: mysql.yml
            service: amas2-mysql
